[versions]
managed-flyway = "8.5.13"

gorm-hibernate = "7.3.0"
persistence-api = '2.2'

[libraries]
managed-flyway = { module = "org.flywaydb:flyway-core", version.ref = "managed-flyway" }
managed-flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "managed-flyway" }
managed-flyway-sqlserver = { module = "org.flywaydb:flyway-sqlserver", version.ref = "managed-flyway" }

grails-datastore-gorm-hibernate5 = { module = "org.grails:grails-datastore-gorm-hibernate5", version.ref = "gorm-hibernate" }

h2 = { module = "com.h2database:h2" }

persistence-api = { module = 'javax.persistence:javax.persistence-api', version.ref = 'persistence-api'}
