[versions]
micronaut-docs = "2.0.0"
micronaut = "4.0.0-M1"
micronaut-test = "4.0.0-SNAPSHOT"
micronaut-sql = "5.0.0-M1"
micronaut-gradle-plugin = "4.0.0-SNAPSHOT"

managed-flyway = "9.16.3"

gorm-hibernate = "7.3.1"
graal-svm = "22.3.2"
persistence-api = '2.2'
groovy = "4.0.9"
spock = "2.3-groovy-4.0"

[libraries]
managed-flyway = { module = "org.flywaydb:flyway-core", version.ref = "managed-flyway" }
managed-flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "managed-flyway" }
managed-flyway-sqlserver = { module = "org.flywaydb:flyway-sqlserver", version.ref = "managed-flyway" }

grails-datastore-gorm-hibernate5 = { module = "org.grails:grails-datastore-gorm-hibernate5", version.ref = "gorm-hibernate" }
graal-svm = { module = "org.graalvm.nativeimage:svm", version.ref = "graal-svm" }

micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }

gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }

persistence-api = { module = 'javax.persistence:javax.persistence-api', version.ref = 'persistence-api'}
